# Generated by Django 4.0.1 on 2022-01-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('tfidf_unigram_acc', models.IntegerField()),
                ('tfidf_brigram_acc', models.IntegerField()),
                ('tfidf_trigram_acc', models.IntegerField()),
                ('tfidf_unigram_time', models.CharField(max_length=100)),
                ('tfidf_brigram_time', models.CharField(max_length=100)),
                ('tfidf_trigram_time', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
