# Generated by Django 4.0.1 on 2022-02-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_modelresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelresult',
            name='tfidf_brigram_acc',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='modelresult',
            name='tfidf_brigram_time',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='modelresult',
            name='tfidf_trigram_acc',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='modelresult',
            name='tfidf_trigram_time',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='modelresult',
            name='tfidf_unigram_acc',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='modelresult',
            name='tfidf_unigram_time',
            field=models.CharField(default='', max_length=100),
        ),
    ]
