# Generated by Django 4.0.1 on 2022-02-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0005_alter_modelresult_tfidf_brigram_acc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelresult',
            name='tfidf_brigram_acc',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='modelresult',
            name='tfidf_brigram_time',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='modelresult',
            name='tfidf_trigram_acc',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='modelresult',
            name='tfidf_trigram_time',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='modelresult',
            name='tfidf_unigram_acc',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='modelresult',
            name='tfidf_unigram_time',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
