# Generated by Django 4.0.1 on 2022-02-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0007_rename_tfidf_brigram_acc_modelresult_tfidf_bigram_acc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelresult',
            name='tfidf_bigram_acc',
        ),
        migrations.RemoveField(
            model_name='modelresult',
            name='tfidf_bigram_time',
        ),
        migrations.AddField(
            model_name='modelresult',
            name='tfidf_brigram_acc',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='modelresult',
            name='tfidf_brigram_time',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='modelresult',
            name='tfidf_trigram_acc',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='modelresult',
            name='tfidf_trigram_time',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='modelresult',
            name='tfidf_unigram_acc',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='modelresult',
            name='tfidf_unigram_time',
            field=models.CharField(default='', max_length=100),
        ),
    ]
